### ISSUE TITLE
Do we need "retrieve" process?

### ISSUE THREAD

**Issue by agstephens** [roocs/roocs-wps-demo#2]
@cehbrecht , thanks for setting up this demo WPS. Do you think we need a "retrieve" process?

I was thinking that "retrieve" is just a case of "subset" where you want the whole data set. And since we  are using the aggregation I thought we would push all the data through Xarray and chunk the output files, and deliver those to the user.

We can discuss later.

**Comment by cehbrecht** [comment]
I have just added it because it was in the json example.

**Comment by cehbrecht** [comment]
removed retrieve in PR #4.
